services:
  melody-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: melody-app
    volumes:
      - ./:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    working_dir: /app
    command: python src/main.py